name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 23.x]
      fail-fast: false  # Don't fail all builds if one version breaks

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install  # Changed from `npm ci` to `npm install`

    - name: Install Grunt CLI globally
      run: npm install -g grunt-cli || echo "Skipping Grunt install"

    - name: Run Grunt build
      run: grunt || echo "Grunt failed on Node ${{ matrix.node-version }}, skipping..."
